# These are supported funding model platforms

github: [johnDoe, janeSmith] # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: johnDoePatreon # Replace with a single Patreon username
open_collective: johnDoeCollective # Replace with a single Open Collective username
ko_fi: johnDoeKoFi # Replace with a single Ko-fi username
tidelift: npm/johnDoePackage # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: johnDoeProject # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: johnDoeLiberapay # Replace with a single Liberapay username
issuehunt: johnDoeIssueHunt # Replace with a single IssueHunt username
lfx_crowdfunding: johnDoeCrowdfunding # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: johnDoePolar # Replace with a single Polar username
buy_me_a_coffee: johnDoeCoffee # Replace with a single Buy Me a Coffee username
custom: ['https://www.paypal-mobilemoney.com/m-pesa'] # Custom funding link
