version: '3.4'

services:
  lms:
    image: lms
    build:
      context: .
      dockerfile: ./Dockerfile
              - name: Docker build and push
                uses: cloudposse/github-action-docker-build-push@1.16.0
            